## To pass this checkpoint you should have access to the data for your project and be able to describe the data structure. How you collected the data and a description of the data should be documented and submitted as a Jupyter Notebook. Submit the GitHub link to your notebook to complete this assignment.

### Describe the Data and Data Structure / How did You Collect the Data?

For this project, I am using the online ranking data/ infoboxes from "The Numbers" on the Grosses for movies of different Genres in 2025. To get this data off the website, I loaded the table into my Panda Dataframe.(See below code for method) The main columns I am going to use are the ranking, movie title, genre, and overall gross revenue. The data structure is in the form of a ranked list. The data includes the Rank of the movie (1,2,3 etc) as well as the Movie title. This data also has the year the movie was released, and the lifetime gross of the movie. Another important part of this table is the genre of the movie, since that plays very highly into my hypothesis of comedy genre movies perform better and have higher gross than horror movies. 

For this data , I have 579 rows of movie data (or 579 movies)(it goes up to 580 on my table, but it starts at 0 and has two extra rows at the end for total tickets sold and total gross of all movies that I could not figure out how to get rid of. I made a chart showing the breakdown of each genre of movie. There are 14 movie genre types in the list I have. The mode for the genre is Drama, as it was the most common in the dataset and appeared 162 times. The minimum or least seen genre in the dataset was educational with only one movie in the top grossing list for the year 2025. 

As I go futher into this project, I will analyze the data and dive deeper into it in order to give me a better understanding and look at things such as if there were more horror or comedies in the list, and also how much gross each made. Just because there were more horror movies in the list of top grossing movies , does not mean they made more overall compared to comedy - it depends where they rank in the list for total gross.

In [45]:
import pandas as pd

# load in the link from the website
html = requests.get(
    "https://www.the-numbers.com/market/2025/top-grossing-movies",
    headers={"User-Agent": "Mozilla/5.0"} #I needed to use AI for some help with this part , as the code does not run without it - I was getting an error.
).text

#read the link
df = pd.read_html(html)[0]

# get rid of the columns I do not want - the number of tickets sold and the distributor for the movie.
df = df.drop(columns=["Tickets Sold"], errors="ignore")
df = df.drop(columns=["Distributor"], errors="ignore")

#show the table
display(df)

# make the table for the frequency of the genres appearing
Table = df["Genre"].value_counts().reset_index()
Table.columns = ["Genre", "Number of Movies"]

#show the table
display(Table)

/var/folders/t3/0wr85tm13x59vdw4hg5br_rr0000gn/T/ipykernel_99058/3183492668.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(html)[0]

,Rank,Movie,Release Date,Genre,2025 Gross
0,1,A Minecraft Movie,"Apr 4, 2025",Adventure,"$423,949,195"
1,2,Lilo & Stitch,"May 23, 2025",Adventure,"$423,778,855"
2,3,Superman,"Jul 11, 2025",Action,"$354,184,465"
3,4,Jurassic World Rebirth,"Jul 2, 2025",Action,"$339,640,400"
4,5,Sinners,"Apr 18, 2025",Horror,"$279,653,537"
...,...,...,...,...,...
576,577,Turno Nocturno,"Apr 18, 2025",Horror,$669
577,578,Il Corpo,"Aug 22, 2025",Thriller/Suspense,$633
578,579,The Birds Who Fear Death,"Mar 21, 2025",Drama,$527
579,Total Gross of All Movies,Total Gross of All Movies,Total Gross of All Movies,Total Gross of All Movies,"$7,352,956,134"
580,Total Tickets Sold,Total Tickets Sold,Total Tickets Sold,Total Tickets Sold,Total Tickets Sold

                        Genre  Number of Movies
0                       Drama               162
1           Thriller/Suspense                69
2                 Documentary                69
3                      Action                62
4                      Comedy                61
5                      Horror                54
6                   Adventure                40
7                     Musical                16
8                Black Comedy                16
9             Romantic Comedy                14
10            Concert/Perfor…                 8
11                    Western                 3
12            Multiple Genres                 2
13                Educational                 1
14  Total Gross of All Movies                 1
15         Total Tickets Sold                 1